version: '3.5'

services:
  rclone:
    build:
      context: .
    environment:
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - REMOTE_SERVICE=${REMOTE_SERVICE}
      - REMOTE_FOLDER=${REMOTE_FOLDER}
      - CRON_EXPRESION=${CRON_EXPRESION}
      - REMOTE_KEEP_TIME=${REMOTE_KEEP_TIME:-5d}
    volumes:
      - ./:/root/.config/rclone
    restart: unless-stopped

